<div class="content-header">
   <h3 class="icon-head head-pergroup-list"><?php echo $this->getHeaderText() ?></h3>
   <p class="content-buttons form-buttons">
		 <?php echo $this->getBackButtonHtml(); ?>
		 <?php echo $this->getResetButtonHtml(); ?>
		 <?php echo $this->getSaveButtonHtml(); ?>
		 <?php if($this->getEditMode()): ?>
		 <?php echo $this->getDeleteButtonHtml(); ?>
		 <?php endif ?>
    </p>
</div>
<form action="<?php echo $this->getSaveUrl() ?>" method="post" id="pergroup_group_edit_form">
    <?php echo $this->getBlockHtml('formkey')?>
    <?php echo $this->getForm() ?>
</form>
<script type="text/javascript">
//<![CDATA[
    var groupForm = new varienForm('pergroup_group_edit_form');
    var groupControl = {
        init: function () {
        	if ($('convert_button_back')) {
        		$('convert_button_back').hide();
        	}
        },
        save: function() {
            groupForm.submit();
            return false;
        },
        deleteTemplate: function() {
            if(window.confirm("<?php echo Mage::helper('LKC_PerGroupShipping')->__('Are you sure that you want to delete this group?') ?>")) {
               	window.location.href = '<?php echo $this->getDeleteUrl() ?>';
            }
        }
    };
    groupControl.init();
//]]>
</script>
