<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td style="width:50%;">
                <h3 class="icon-head head-group-list">
                    <?php echo $this->getHeaderText() ?>
                </h3>
            </td>
            <td class="form-buttons">
                <button class="scalable add" onclick="window.location='<?php echo $this->getCreateUrl() ?>'">
                    <span>
                        <?php echo Mage::helper('Lokey_PerGroupShipping/Data')->__('Add New Group'); ?>
                    </span>
                </button>
            </td>
        </tr>
    </table>
</div>
<div>
    <?php echo $this->getChildHtml('grid') ?>
</div>
